### ISSUE TITLE
It cannot find the apk if there is a space in the name

### ISSUE THREAD

**Issue by Drjacky** [viralvaghela/secret-finder#1]
The path:
`/Users/usernameee/Desktop/example\ 2.apk`

> Failed to decompile APK.
Input file (/Users/usernameee/Desktop/example\ 2.apk ) was not found or was not readable.

**Comment by viralvaghela** [comment]
Thank you @Drjacky for reporting this issue,I wasn't aware of this,will try to update and fix it soon

**Comment by Drjacky** [comment]
This is the name of the file: `example-pulled 2.apk`
and this is the error:
```bash
Select file check option
1. Basic Scan(Fast - Check for only important)
2. Advance Scan(Slow - Check for All files): 1
Decompiling APK: example-pulled\ 2.apk  It may take some time, please wait...

Failed to decompile APK.
Input file (example-pulled\ 2.apk ) was not found or was not readable.

Searching for sensitive strings in all files...

Progress:   0%|                                                                                        | 0/2 [00:00<?, ?file/s]Traceback (most recent call last):
  File "/secret-finder/secret_finder.py", line 188, in <module>
    main()
  File "/secret-finder/secret_finder.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/secret-finder/secret_finder.py", line 169, in main
    sensitive_matches = check_apk_for_sensitive_keywords(apk_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/secret-finder/secret_finder.py", line 149, in check_apk_for_sensitive_keywords
    strings_matches = check_file_for_sensitive_keywords(strings_xml_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/secret-finder/secret_finder.py", line 99, in check_file_for_sensitive_keywords
    with open(file_path, 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/secret-finder/example-pulled\\_2_decompiled/res/values/strings.xml'
Progress:   0%|                                                                                        | 0/2 [00:00<?, ?file/s]
```
